// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg3YjDIc6iVzXLyNw7tXpqSrXm9ql45zk',
    appId: '1:568477673502:web:92002fdfd7be5777e7660f',
    messagingSenderId: '568477673502',
    projectId: 'm3an3an1',
    authDomain: 'm3an3an1.firebaseapp.com',
    storageBucket: 'm3an3an1.firebasestorage.app',
    measurementId: 'G-F9HW3H2PJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg3YjDIc6iVzXLyNw7tXpqSrXm9ql45zk',
    appId: '1:568477673502:android:6e1b4f7c9a8b5d4c3e7660f',
    messagingSenderId: '568477673502',
    projectId: 'm3an3an1',
    authDomain: 'm3an3an1.firebaseapp.com',
    storageBucket: 'm3an3an1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg3YjDIc6iVzXLyNw7tXpqSrXm9ql45zk',
    appId: '1:568477673502:ios:6e1b4f7c9a8b5d4c3e7660f',
    messagingSenderId: '568477673502',
    projectId: 'm3an3an1',
    authDomain: 'm3an3an1.firebaseapp.com',
    storageBucket: 'm3an3an1.firebasestorage.app',
    iosBundleId: 'com.example.manager3an3an',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg3YjDIc6iVzXLyNw7tXpqSrXm9ql45zk',
    appId: '1:568477673502:ios:6e1b4f7c9a8b5d4c3e7660f',
    messagingSenderId: '568477673502',
    projectId: 'm3an3an1',
    authDomain: 'm3an3an1.firebaseapp.com',
    storageBucket: 'm3an3an1.firebasestorage.app',
    iosBundleId: 'com.example.manager3an3an',
  );
}